[project]
name = "hw2"
version = "0.1.0"
description = "This is the 2nd homework of this course."
authors = [
    {name = "singularitti", email = "singularitti@outlook.com"},
]
dependencies = [
    "numpy>=1.26.4",
    "scipy>=1.13.1",
    "matplotlib>=3.9.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
